/*
 * tools/fonts.mjs — fetch the shipped faces. Run: node tools/fonts.mjs
 *
 * TYPESTRACT ships its type: the faces below are pulled from Google
 * Fonts as latin + latin-ext woff2 subsets and written under fonts/,
 * each family beside its SIL Open Font License, with fonts/fonts.css
 * (the @font-face rules, pointing at the local files) and
 * fonts/manifest.json (provenance: what was fetched, from where, when).
 * The site never talks to a font CDN; this tool is how the shelf is
 * restocked, and it is the only network in the repository.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'fonts');
const CSS_API = 'https://fonts.googleapis.com/css2';
const OFL_RAW = 'https://raw.githubusercontent.com/google/fonts/main/ofl';
const SUBSETS = ['latin', 'latin-ext'];
// a browser that is served woff2 with unicode-range subsets
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0 Safari/537.36';

/* The shelf. `specs` are tried in order — a variable-font axis range
 * first, the static instances when the family has no variable build.
 * `dir` is the family's directory in the google/fonts repository. */
const FAMILIES = [
  { family: 'Libre Baskerville', dir: 'librebaskerville', specs: ['ital,wght@0,400;0,700;1,400'] },
  { family: 'Jost', dir: 'jost', specs: ['ital,wght@0,100..900;1,100..900'] },
  { family: 'Courier Prime', dir: 'courierprime', specs: ['ital,wght@0,400;0,700;1,400;1,700'] },
  { family: 'EB Garamond', dir: 'ebgaramond', specs: ['ital,wght@0,400..800;1,400..800'] },
  { family: 'Cabin', dir: 'cabin', specs: ['ital,wght@0,400..700;1,400..700'] },
  { family: 'Bodoni Moda', dir: 'bodonimoda', specs: ['ital,opsz,wght@0,6..96,400..900;1,6..96,400..900', 'ital,wght@0,400..900;1,400..900'] },
  { family: 'Archivo', dir: 'archivo', specs: ['ital,wght@0,100..900;1,100..900'] },
  { family: 'Alegreya', dir: 'alegreya', specs: ['ital,wght@0,400..900;1,400..900'] },
  { family: 'Alegreya Sans', dir: 'alegreyasans', specs: ['ital,wght@0,400;0,700;1,400'] },
  { family: 'Crimson Pro', dir: 'crimsonpro', specs: ['ital,wght@0,200..900;1,200..900'] },
  { family: 'Nunito Sans', dir: 'nunitosans', specs: ['ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000', 'ital,wght@0,200..1000;1,200..1000'] },
  { family: 'Cutive', dir: 'cutive', specs: [''] },
  { family: 'IBM Plex Serif', dir: 'ibmplexserif', specs: ['ital,wght@0,400;0,700;1,400'] },
  { family: 'IBM Plex Sans', dir: 'ibmplexsans', specs: ['ital,wght@0,400;0,700;1,400'] },
  { family: 'IBM Plex Mono', dir: 'ibmplexmono', specs: ['ital,wght@0,400;0,700;1,400'] },
  { family: 'Spectral', dir: 'spectral', specs: ['ital,wght@0,400;0,700;1,400'] },
  { family: 'Source Sans 3', dir: 'sourcesans3', specs: ['ital,wght@0,200..900;1,200..900'] },
];

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-');

async function fetchCSS(family, spec) {
  const q = `family=${encodeURIComponent(family).replace(/%20/g, '+')}${spec ? ':' + spec : ''}&display=swap`;
  const res = await fetch(`${CSS_API}?${q}`, { headers: { 'User-Agent': UA } });
  if (!res.ok) return null;
  return res.text();
}

/** Parse the CSS API's answer into { subset, style, weight, range, url } rows. */
function parseFaces(css) {
  const rows = [];
  const re = /\/\* (\S+) \*\/\s*@font-face \{([^}]+)\}/g;
  let m;
  while ((m = re.exec(css))) {
    const [, subset, body] = m;
    const get = (k) => (body.match(new RegExp(`${k}:\\s*([^;]+);`)) || [])[1]?.trim();
    const url = (body.match(/url\(([^)]+)\)/) || [])[1];
    rows.push({ subset, style: get('font-style'), weight: get('font-weight'), range: get('unicode-range'), url });
  }
  return rows;
}

async function main() {
  fs.mkdirSync(OUT, { recursive: true });
  const manifest = { fetched: new Date().toISOString().slice(0, 10), source: 'Google Fonts (fonts.googleapis.com css2 API), latin + latin-ext subsets', license: 'SIL Open Font License 1.1 — see each family’s OFL.txt', families: [] };
  const cssOut = [
    '/* fonts/fonts.css — generated by tools/fonts.mjs; do not edit by hand.',
    ' * Every face here is licensed under the SIL Open Font License 1.1;',
    ' * the license text sits beside each family. */',
    '',
  ];
  let total = 0;
  for (const fam of FAMILIES) {
    let css = null, used = null;
    for (const spec of fam.specs) {
      css = await fetchCSS(fam.family, spec);
      if (css) { used = spec; break; }
    }
    if (!css) { console.error(`FAIL ${fam.family}: the CSS API refused every spec`); process.exitCode = 1; continue; }
    const faces = parseFaces(css).filter((f) => SUBSETS.includes(f.subset));
    if (!faces.length) { console.error(`FAIL ${fam.family}: no latin faces in the answer`); process.exitCode = 1; continue; }
    const dir = path.join(OUT, slug(fam.family));
    fs.mkdirSync(dir, { recursive: true });
    const entry = { family: fam.family, spec: used, files: [] };
    let famBytes = 0;
    for (const f of faces) {
      const name = `${slug(fam.family)}-${f.weight.replace(/\s+/g, '-')}-${f.style}-${f.subset}.woff2`;
      const res = await fetch(f.url, { headers: { 'User-Agent': UA } });
      if (!res.ok) { console.error(`FAIL ${fam.family}: ${f.url} → ${res.status}`); process.exitCode = 1; continue; }
      const buf = Buffer.from(await res.arrayBuffer());
      fs.writeFileSync(path.join(dir, name), buf);
      famBytes += buf.length;
      entry.files.push({ file: `${slug(fam.family)}/${name}`, bytes: buf.length, from: f.url });
      cssOut.push(
        `@font-face {`,
        `  font-family: '${fam.family}';`,
        `  font-style: ${f.style};`,
        `  font-weight: ${f.weight};`,
        `  font-display: swap;`,
        `  src: url(${slug(fam.family)}/${name}) format('woff2');`,
        `  unicode-range: ${f.range};`,
        `}`,
      );
    }
    // the license, from the google/fonts repository
    const ofl = await fetch(`${OFL_RAW}/${fam.dir}/OFL.txt`);
    if (ofl.ok) fs.writeFileSync(path.join(dir, 'OFL.txt'), await ofl.text());
    else { console.error(`FAIL ${fam.family}: no OFL.txt at ${fam.dir}`); process.exitCode = 1; }
    entry.bytes = famBytes;
    manifest.families.push(entry);
    total += famBytes;
    console.log(`ok  ${fam.family.padEnd(20)} ${String(entry.files.length).padStart(2)} files  ${(famBytes / 1024).toFixed(0).padStart(5)} KB  (${used || 'static regular'})`);
  }
  fs.writeFileSync(path.join(OUT, 'fonts.css'), cssOut.join('\n') + '\n');
  fs.writeFileSync(path.join(OUT, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
  console.log(`\n${manifest.families.length} families, ${(total / 1024).toFixed(0)} KB on the shelf`);
}

main();
